[app]
name = "MD Updater"

category = "Badge"

[metadata]
author = "Matthew Wilkes"

# License of your app as an SPDX identifier: <https://spdx.org/licenses/>
license = "LGPL-3.0-only"

# URL to the repository of your app.
url = "https://www.github.com/username/repo"

# Description of your app.  Maximum 140 characters!
description = "A utility to update the firmware of the Megadrive interface hexpansion"

version = "2.0.1"